### ISSUE TITLE
Getting error while enabling plugins

### ISSUE THREAD

**Issue by oyvindfo** [rockandska/ansible-role-rabbitmq#22]
Getting the following error when running my playbook 

```
TASK [rockandska.rabbitmq : [RabbitMQ] Enable plugins] ***************************************************************************************************************************
fatal: [mongo4]: FAILED! => {"changed": false, "cmd": "/usr/sbin/rabbitmq-plugins enable --online rabbitmq_management", "msg": "Error: this command requires the target node to be running.\nArguments given:\n\tenable --online rabbitmq_management\n\n\u001b[1mUsage\u001b[0m\n\nrabbitmq-plugins [--node <node>] [--longnames] [--quiet] enable <plugin1> [ <plugin2>] | --all [--offline] [--online]", "rc": 64, "stderr": "Error: this command requires the target node to be running.\nArguments given:\n\tenable --online rabbitmq_management\n\n\u001b[1mUsage\u001b[0m\n\nrabbitmq-plugins [--node <node>] [--longnames] [--quiet] enable <plugin1> [ <plugin2>] | --all [--offline] [--online]\n", "stderr_lines": ["Error: this command requires the target node to be running.", "Arguments given:", "\tenable --online rabbitmq_management", "", "\u001b[1mUsage\u001b[0m", "", "rabbitmq-plugins [--node <node>] [--longnames] [--quiet] enable <plugin1> [ <plugin2>] | --all [--offline] [--online]"], "stdout": "", "stdout_lines": []}
```

If I rerun the playbook, it works. Here is my playbook:

```
- name: Install rabbitmq master
  hosts: rabbitmq_master_server
  become: true
  roles:
    - { role: rockandska.erlang, erlang_series: 23 }
    - role: rockandska.rabbitmq
      vars:
        rabbitmq_is_master: true
        rabbitmq_plugins_to_enable:
            - rabbitmq_management
            - rabbitmq_shovel
        rabbitmq_users_to_create:
          - user: admin
            password: admin
            vhost: /
            configure_priv: .*
            read_priv: .*
            write_priv: .*
            tags: administrator
        rabbitmq_users_to_delete:
          - guest

```
