### ISSUE TITLE
Could not determine the version of the RabbitMQ server

### ISSUE THREAD

**Issue by charnet1019** [rockandska/ansible-role-rabbitmq#29]
ansible version: 2.12.6

playbook:
```
---

- hosts: demo
  gather_facts: yes

  roles:
    - role: erlang
      vars:
        erlang_series: 23
        erlang_series_rpm_version: 23.3.4.11-1.el7
    - role: rabbitmq
      vars:
        rabbitmq_series: 3.8
        rabbitmq_series_rpm_version: 3.8.30
        #rabbitmq_sysctl_config:
        #  listeners:
        #    tcp:
        #      default: 5673    # http web port
        #  tcp_listen_options:
        #    linger:
        #      'on': "true"
        rabbitmq_erlang_config: |
          {rabbit, [
             {tcp_listeners, [{"{{ ansible_default_ipv4['address'] }}", 5672}]}
            ]
          }
        rabbitmq_env_config:
          NODENAME: "{{ ansible_nodename }}"
        rabbitmq_node_name:
          rabbitmq_node_name: "{{ ansible_nodename }}"
        rabbitmq_users_to_create:
          - user: admin
            password: admin
            vhost: /
            configure_priv: .*
            read_priv: .*
            write_priv: .*
            tags: administrator
        #rabbitmq_users_to_delete:
        #  - guest
        rabbitmq_plugins_to_enable:
          - rabbitmq_management
        rabbitmq_management_user: 'webadmin'
        rabbitmq_management_password: 'secret'
        rabbitmq_management_host: "{{ ansible_default_ipv4['address'] }}"
        rabbitmq_hide_log: false
  tags:
    - rabbitmq
```
